name: Publish package

on:
  push:
  pull_request:
    paths:
      - ./src/**
      - ./test/**
      - ./bun.lock
      - ./package.json
      - ./nuxt.config.ts
      - ./.github/workflows/publish.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUN_VERSION: 1.2.5

defaults:
  run:
    shell: bash
    working-directory: ./ # Ensure bun install runs in the correct working directory

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

        with:
          bun-version: ${{ env.BUN_VERSION }}

      # Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

      - name: Lint
        run: bun run lint

  typechecking:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

      - name: Typecheck
        run: bun run typecheck

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

      - name: Playground prepare
        run: bun run dev:prepare

      - name: Test
        run: bun run test

  publish:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
      - typechecking
      - test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

      - name: Prepare
        run: |
          bun run prepack
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            changelogen --release
          elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            changelogen --prerelease
          fi

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: |
            if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              latest
            elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
              beta
            fi
